# Generated by Django 6.0 on 2025-12-21 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='Symbol z XTB, np. PKN.PL', max_length=20, unique=True)),
                ('yahoo_ticker', models.CharField(help_text='Symbol z Yahoo, np. PKN.WA', max_length=20)),
                ('currency', models.CharField(default='PLN', help_text='Waluta notowania, np. PLN, EUR', max_length=3)),
                ('name', models.CharField(blank=True, help_text='Pełna nazwa, np. Orlen S.A.', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Mój IKE', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xtb_id', models.CharField(help_text='Unikalny ID operacji z pliku XTB', max_length=50, unique=True)),
                ('date', models.DateTimeField()),
                ('type', models.CharField(choices=[('BUY', 'Kupno'), ('SELL', 'Sprzedaż'), ('DEPOSIT', 'Wpłata'), ('DIVIDEND', 'Dywidenda'), ('OTHER', 'Inne')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Kwota transakcji w walucie konta', max_digits=15)),
                ('quantity', models.DecimalField(decimal_places=4, default=0, help_text='Liczba akcji', max_digits=15)),
                ('comment', models.TextField(blank=True, help_text='Oryginalny komentarz z XTB')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.asset')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('close_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='core.asset')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('asset', 'date')},
            },
        ),
    ]
