# Generated by Django 6.0 on 2025-12-21 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='currency',
            field=models.CharField(default='PLN', help_text='Currency, e.g., PLN, EUR', max_length=3),
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(blank=True, help_text='Full name, e.g., Orlen S.A.', max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='symbol',
            field=models.CharField(help_text='XTB Symbol, e.g., PKN.PL', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='yahoo_ticker',
            field=models.CharField(help_text='Yahoo Symbol, e.g., PKN.WA', max_length=20),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='name',
            field=models.CharField(default='My IKE', max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Transaction amount in account currency', max_digits=15),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='comment',
            field=models.TextField(blank=True, help_text='Original comment from XTB'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='quantity',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Number of shares', max_digits=15),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('DEPOSIT', 'Deposit'), ('DIVIDEND', 'Dividend'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='xtb_id',
            field=models.CharField(help_text='Unique operation ID from XTB', max_length=50, unique=True),
        ),
    ]
