# Generated by Django 6.0 on 2025-12-22 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='last_price',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='asset',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='currency',
            field=models.CharField(default='PLN', max_length=10),
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='symbol',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='yahoo_ticker',
            field=models.CharField(max_length=20),
        ),
    ]
