# Generated by Django 6.0 on 2025-12-23 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_asset_last_price_asset_last_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='previous_close',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
    ]
