# Generated by Django 6.0 on 2025-12-26 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_asset_previous_close'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='currency',
            field=models.CharField(default='PLN', max_length=3),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_type',
            field=models.CharField(choices=[('IKE', 'IKE (Tax-Free)'), ('IKZE', 'IKZE (Tax-Free)'), ('STANDARD', 'Standard (Taxable)')], default='IKE', max_length=10),
        ),
    ]
