# Generated by Django 6.0 on 2025-12-28 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_portfolio_currency_portfolio_portfolio_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('CLOSE', 'Close Position'), ('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('DIVIDEND', 'Dividend'), ('TAX', 'Tax'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
