# Generated by Django 6.0 on 2026-01-03 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='xtb_id',
            field=models.CharField(max_length=50),
        ),
    ]
