# Generated by Django 6.0 on 2026-01-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_transaction_xtb_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('STOCK', 'Stock'), ('ETF', 'ETF'), ('CRYPTO', 'Cryptocurrency'), ('CURRENCY', 'Currency'), ('COMMODITY', 'Commodity'), ('BOND', 'Bond'), ('OTHER', 'Other')], default='STOCK', max_length=20),
        ),
        migrations.AddField(
            model_name='asset',
            name='isin',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='sector',
            field=models.CharField(choices=[('TECHNOLOGY', 'Technology'), ('FINANCE', 'Financial Services'), ('ENERGY', 'Energy & Utilities'), ('HEALTHCARE', 'Healthcare'), ('CONSUMER', 'Consumer Goods'), ('INDUSTRIAL', 'Industrials'), ('REAL_ESTATE', 'Real Estate'), ('MATERIALS', 'Basic Materials'), ('TELECOM', 'Telecommunications'), ('GAMING', 'Gaming & Entertainment'), ('OTHER', 'Other / Unknown')], default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='last_price',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='previous_close',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='asset',
            name='yahoo_ticker',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='name',
            field=models.CharField(default='My Portfolio', max_length=50),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_type',
            field=models.CharField(choices=[('STANDARD', 'Standard (Taxable)'), ('IKE', 'IKE (Tax-Free)'), ('IKZE', 'IKZE (Tax-Deductible)')], default='STANDARD', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Cashflow in account currency', max_digits=15),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='quantity',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('CLOSE', 'Close Position'), ('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('DIVIDEND', 'Dividend'), ('TAX', 'Tax'), ('FEE', 'Fee'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='xtb_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('portfolio', 'xtb_id')},
        ),
    ]
