# Generated by Django 6.0 on 2026-01-06 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_transaction_options_asset_asset_type_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together=set(),
        ),
    ]
