# Generated by Django 6.0 on 2026-08-10 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_assetfeedback_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='position_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
